# -*- coding: utf-8 -*-
"""Travel Blog

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110kBcwjPIXP1uMAu4i6XideRB0ShDz-G
"""

from IPython.display import HTML

HTML("""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Travel Blog</title>

<style>
*{
    margin:0;
    padding:0;
    box-sizing:border-box;
    font-family:Arial, sans-serif;
}

body{
    background:#f4f4f4;
}

header{
    background:linear-gradient(135deg,#6a11cb,#2575fc);
    color:white;
    text-align:center;
    padding:30px;
}

section{
    padding:20px;
}

.blog-post{
    background:white;
    padding:20px;
    margin-bottom:20px;
    border-radius:10px;
    box-shadow:0 2px 10px rgba(0,0,0,0.1);
}

.gallery{
    display:grid;
    grid-template-columns:repeat(auto-fit,minmax(250px,1fr));
    gap:15px;
}

.gallery img{
    width:100%;
    height:220px;
    object-fit:cover;
    border-radius:10px;
    transition:0.4s;
}

.gallery img:hover{
    transform:scale(1.05);
}

.contact-form{
    background:white;
    padding:20px;
    border-radius:10px;
}

input, textarea{
    width:100%;
    padding:10px;
    margin:10px 0;
}

button{
    background:#2575fc;
    color:white;
    border:none;
    padding:12px 20px;
    cursor:pointer;
    border-radius:5px;
}

button:hover{
    background:#6a11cb;
}

footer{
    background:#333;
    color:white;
    text-align:center;
    padding:15px;
    margin-top:20px;
}
</style>
</head>

<body>

<header>
    <h1>🌍 My Travel Blog</h1>
    <p>Exploring Beautiful Places Around India</p>
</header>

<section>
    <h2>Travel Stories</h2>

    <div class="blog-post">
        <h3>🏞️ Trip to Ooty</h3>
        <p>
            Ooty is famous for its tea gardens, cool climate,
            and beautiful mountain views.
        </p>
    </div>

    <div class="blog-post">
        <h3>🏖️ Visit to Kanyakumari</h3>
        <p>
            Kanyakumari is known for its stunning sunrise,
            sunset, and the meeting of three seas.
        </p>
    </div>
</section>

<section>
    <h2>📸 Photo Gallery</h2>

    <div class="gallery">
        <img src="https://picsum.photos/400/250?1">
        <img src="https://picsum.photos/400/250?2">
        <img src="https://picsum.photos/400/250?3">
        <img src="https://picsum.photos/400/250?4">
    </div>
</section>

<section>
    <h2>📩 Contact Me</h2>

    <div class="contact-form">
        <input type="text" placeholder="Your Name">
        <input type="email" placeholder="Your Email">
        <textarea rows="5" placeholder="Your Message"></textarea>
        <button>Send Message</button>
    </div>
</section>

<footer>
    <p>© 2026 Travel Blog | Created by Kiruthika Shree</p>
</footer>

</body>
</html>
""")